### ISSUE TITLE
can't add timestampsInSnapshots to settings

### ISSUE THREAD

**Issue by delizondo** [firebase/firebase-dart#178] opened 2018-06-18 22:34 UTC
* Dart version: Dart VM version: 2.0.0-dev.63.0 (Fri Jun 15 00:42:43 2018 +0200) on "macos_x64"
* Firebase version: 4.5.0
* OS: macOS 10.13
* IDE: WebStorm 2018.1.15
* Browser: Chrome Version 67.0.3396.87

Today I've updated the Firebase library, including the js scripts to: 

```
<script src="https://www.gstatic.com/firebasejs/4.13.0/firebase.js"></script>
<script src="https://www.gstatic.com/firebasejs/4.13.0/firebase-firestore.js"></script>
````

Now, in the browser console I'm getting the following error: 

```
[2018-06-18T22:23:03.178Z]  @firebase/firestore: Firestore (4.13.0): 
The behavior for Date objects stored in Firestore is going to change
AND YOUR APP MAY BREAK.
To hide this warning and ensure your app does not break, you need to add the
following code to your app before calling any other Cloud Firestore methods:

  const firestore = firebase.firestore();
  const settings = {/* your settings... */ timestampsInSnapshots: true};
  firestore.settings(settings);

With this change, timestamps stored in Cloud Firestore will be read back as
Firebase Timestamp objects instead of as system Date objects. So you will also
need to update code expecting a Date to instead expect a Timestamp. For example:

  // Old:
  const date = snapshot.get('created_at');
  // New:
  const timestamp = snapshot.get('created_at');
  const date = timestamp.toDate();

Please audit all existing usages of Date when you enable the new behavior. In a
future release, the behavior will change to the new behavior, so if you do not
follow these steps, YOUR APP MAY BREAK.
```

I can't find a way to implement the requested settings changes in Dart, the closest I managed to get was this (without getting compilation errors): 

```
    Settings settings = new Settings(host: "timestampsInSnapshots", ssl: true);
    firestore.settings(settings);
```

But obviously is not working, any ideas?

**Comment by kevmoo** [comment] 2018-06-18 23:52
This is just work that needs to happen. @Kleak – have any free time?

**Comment by Kleak** [comment] 2018-06-19 06:18
This is the same as #171. 
Have started looking at it 😉 
Will have a PR soon

**Comment by kevmoo** [comment] 2018-06-20 19:51
Duplicate of #171

**Closed by kevmoo** 2018-06-20 19:51 UTC
Labels: bug
